[images]
  remote_images = ["https://fakestoreapi.com/*", "https://fakestoreapi.com/img/*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
